fix issue#638 : show log message when symbol is defined
Deducteam/lambdapi pull request #1070
Opened 2024-03-28 10:25 UTC by Alidra

As described in issue#638, log messages are sometimes not shown at the right moment when a symbol is defined and proofs are navigated. This PR fixes this issue.

2024-03-28 16:50 UTC, fblanqui requested changes
Thanks for your PR!

2024-03-28 16:50 UTC, fblanqui commented on src/handle/command.ml
> +      (ss, Some pdata, None)
useless diff

2024-03-28 16:50 UTC, fblanqui commented on src/handle/command.ml
> +      in ffff;
Prefer to write:
```
begin
  match pe.elt with
  ...
end;
````

2024-03-28 16:50 UTC, fblanqui commented on src/handle/command.ml
> +      in ffff;
Note that `Stdlib.(!(Stdlib.ref Format.std_formatter))` is the same as `Format.std_formatter`. `ref` creates a pointer to something. `!` returns the thing a pointer points to.
But why not simply writing:
```
| P_proof_abort -> ()
```
?

2024-03-28 16:50 UTC, fblanqui commented on src/handle/command.ml
> +
useless diff

2024-03-28 16:50 UTC, fblanqui commented on src/handle/command.ml
> +      in ffff;
Another remark: please check CONTRIBUTING.md and use misc/git_hook_helper.sh.

2024-03-28 17:01 UTC, fblanqui commented
Hi Abdelghani. From your PR, I understand that the function pdata_finalize should not print anything because it interferes with interfaces. It would be interesting to understand why. But it means that it should not emit warnings too. And indeed, if we add at the end of the file
```
symbol l:A ≔
begin
abort;
```
we get 2 new problems in Emacs (I didn't test VSCode):

1. The abort warning is printed first, before the other messages, while it should be written only when we reach the proof.

2. The green zone disappears and I have an error: `eglot--lsp-position-to-point: Symbol’s function definition is void: eglot-move-to-column`. Can be fixed by merging https://github.com/Deducteam/lambdapi/pull/977?

2024-03-29 10:58 UTC, fblanqui commented
The problems mentioned are solved by #977.

2024-03-29 11:28 UTC, fblanqui commented
Hi. The last commit is better but there is still something wrong. Warnings and messages should not be printed when the pdata_finalize function is created but at the very end of the command.ml file after the evaluation of pdata_finalize itself. One solution is to extend the proof_data record type with a new field pdata_print: unit -> unit, corresponding to your print_fct, and executed at the end of command.ml after pdata_finalize.

2024-03-29 13:31 UTC, Alidra commented
Thanks Frédéric,
It seems to me that messages now are printed at the right place. The same should be done to warnings. 
Actually, Warnings and messages were printed when the pdata_finalize function is evaluated which was giving the issue we are trying to solve. Am I wrong?
I will push new code, please check again and tell me.

2024-03-29 13:55 UTC, fblanqui commented
You should merge origin/master and fix make sanity_check first.

2024-03-29 14:00 UTC, fblanqui commented
The messages are not written in the right order yet. Take for instance:
```
symbol A:TYPE;
symbol l:A ≔
begin
assume x; // fails
abort; // warning
```
The error should appear before the warning.
As explained in my previous message: One solution is to extend the proof_data record type with a new field pdata_print: unit -> unit, corresponding to your print_fct, and executed at the end of command.ml after pdata_finalize.

2024-03-29 16:54 UTC, fblanqui commented
After discussion offline, changes to do in lp_doc.ml:
```
    let st, dg_proof, logs =
      match end_proof pst with
      | Cmd_OK (st, qres)   ->
        let qres = match qres with None -> "OK" | Some x -> x in
        let pg = qed_loc, 4, qres, None in
(* line to add: *)
let logs = ((3, buf_get_and_clear lp_logger), cmd_loc) :: logs in
        st, pg :: dg_proof, logs
```

2024-03-29 21:39 UTC, Alidra commented
Hi Frédéric,
The issue described in 638 seems fixed.
It worth mentioning though that navigating the proofs before the proof is completed (ended, aborted or admitted) prevents any logs from  being displayed. This behavior is prior to the current fix.
Does this seem fine to you?

2024-03-30 08:05 UTC, fblanqui commented
Could you please provide an example?

2024-03-30 08:52 UTC, Alidra commented
Here is an example : 
```
verbose 3;
symbol T : TYPE;
symbol trivial : T → T → T → T
≔ begin
  assume _ _ x;
  refine x;
```
In this case, navigating the proofs doesn't show any log. putting end at the end of the proof show the logs again.
Note also that logs are shown when the check is run in the command line :
```
lambdapi check tests/OK/anonymous2.lp 
Checking "/home/abdelghani/Repos/forksLambdapi/lambdapi/tests/OK/anonymous2.lp" ...
verbose 3
/home/abdelghani/Repos/forksLambdapi/lambdapi/tests/OK/anonymous2.lp:2:0-16
symbol T : TYPE
[/home/abdelghani/Repos/forksLambdapi/lambdapi/tests/OK/anonymous2.lp:8:0] Unexpected token: "".
```

2024-03-30 10:43 UTC, fblanqui commented
This is because there is no terminator to your begin. Or did you forget it in your example?
If you had abort, it works fine. But an error should be omitted if there is no terminator, like on command line:
```
11:40 ~/src/lambdapi (fix/logMessages) lambdapi check tmp/638b.lp 
Checking "/home/blanqui/src/lambdapi/tmp/638b.lp" ...
verbose 3
/home/blanqui/src/lambdapi/tmp/638b.lp:2:0-16
symbol T : TYPE
[/home/blanqui/src/lambdapi/tmp/638b.lp:7:0] Unexpected token: "".
```
But even on command line, the error message is incorrect. It should complain that there is no end/admitted/abort.
Please create a new issue for this.

2024-03-30 10:48 UTC, fblanqui commented
make sanity_check fails:
```
11:41 ~/src/lambdapi (fix/logMessages) make sanity_check
In src/handle/command.ml, line 498 more than 78 characters...
In src/handle/command.ml, line 524 more than 78 characters...
In src/handle/command.ml, line 538 more than 78 characters...
In src/handle/command.ml, line 540 has trailing spaces...
```

2024-03-30 11:04 UTC, Alidra commented
> This is because there is no terminator to your begin. Or did you forget it in your example? If you had abort, it works fine.
Yes. But running Lambdapi in command line with the same file shows the log messages. Shouldn't it be the same with LSP.

> But an error should be omitted if there is no terminator, like on command line:
> 
> ```
> 11:40 ~/src/lambdapi (fix/logMessages) lambdapi check tmp/638b.lp 
> Checking "/home/blanqui/src/lambdapi/tmp/638b.lp" ...
> verbose 3
> /home/blanqui/src/lambdapi/tmp/638b.lp:2:0-16
> symbol T : TYPE
> [/home/blanqui/src/lambdapi/tmp/638b.lp:7:0] Unexpected token: "".
> ```
> 
> But even on command line, the error message is incorrect. It should complain that there is no end/admitted/abort. Please create a new issue for this.
Ok.

2024-03-30 11:09 UTC, Alidra commented
> make sanity_check fails:
> 
> ```
> 11:41 ~/src/lambdapi (fix/logMessages) make sanity_check
> In src/handle/command.ml, line 498 more than 78 characters...
> In src/handle/command.ml, line 524 more than 78 characters...
> In src/handle/command.ml, line 538 more than 78 characters...
> In src/handle/command.ml, line 540 has trailing spaces...
> ```

I dont see these errors in my side  (for instance line 498 in command.ml is 59 characters long only)

2024-03-30 11:32 UTC, fblanqui commented
My branch was not update. Sorry.

2024-03-30 11:42 UTC, merged